### PR TITLE
Migrate Example Project from Cocoapods to XcodeGen

### LINKED ISSUE #9: Stop shipping the pods in the example project
There's a lot of diff when we edit the example project. We can instead generate the project and have the CI attempt to build and run the pods.

### PR DESCRIPTION
**Pull request by ffittschen**
## Description

As discussed in #9, this PR removes the Pods from being shipped with the ExampleProject. Since I could not find a way to generate a Xcode project that contains an application target using Swift Package Manager, I used [XcodeGen](https://github.com/yonaskolb/XcodeGen) to generate the project.

I also updated the `ci.yml` to install XcodeGen. I chose to install it without updating Homebrew to reduce the time it takes, but if you'd rather install it with updating Homebrew, I can remove the env variable again.

Resolves #9.

### CODE REVIEW

**Comment by rockbruno** [comment]
Looks great! Is there a ruby version of it so we can put it in a Gemfile or something similar? The way it works right now someone downloading this repo would have to manually download xcodegen to work with the example project. Would be cool if a makefile in the example folder treated that too, so if there's a gem of it it would be easier than using brew.

**Comment by ffittschen** [comment]
I think `brew` is the easiest option. XcodeGen is actually written in Swift, so the only other options would be to clone the repo and call `swift run xcodegen`. But I just added some documentation to explain how to use generate the project.

**Comment by ffittschen** [comment]
Okay, I think I found a workaround to not use brew: By creating a `Package.swift` with XcodeGen as dependency and a dummy target with an empty Swift file that "depends" on the executable product from XcodeGen, it is possible to call `swift run xcodegen` from within the `ExampleProject` folder. 

What do you think @rockbruno ? 

```swift
// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "XcodeGenWrapper",
    platforms: [.macOS(.v10_13)],
    dependencies: [
        .package(url: "https://github.com/yonaskolb/XcodeGen.git", from: "2.18.0")
    ],
    targets: [
        .target(
            name: "Dummy",
            dependencies: ["xcodegen"],
            path: "Resources"
        )
    ]
)
```

**Comment by rockbruno** [comment]
I think the SPM option is great! Makes it easier to setup the project :)

**Comment by ffittschen** [comment]
Cool 👍🏻 I added the SPM way as an alternative option

**Comment by rockbruno** [comment]
Can we keep it as the main one? I think we don't need the brew one.

**Comment by ffittschen** [comment]
Only SPM is also fine with me, but I'd argue that it doesn't hurt to provide brew as an option for those who would prefer it.

**Comment by rockbruno** [comment]
We can mention it in the comments, but for version control reasons SPM is better because Brew has no decent ways of locking dependencies to a specific working version.

**Review by rockbruno — APPROVED** [review]
I didn't noticed the docs were already mentioned it all so this looks good to merge!

**Comment by rockbruno** [comment]
Thanks a lot! 🎉

**Pull request merged**
